### ISSUE TITLE
gateway timeout

### ISSUE THREAD

**Issue by guntars00** [axle-h/Axh.Fit.Endomondo#1]
Axh.Fit.Endomondo.exe -u 3F611A4C3CDBDBF8.....
Found account id: 27....

Unhandled Exception: System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at Axh.Fit.Endomondo.EndomondoScraper.GetHistory(Int32 userId)
   at Axh.Fit.Endomondo.Program.Main(String[] args)

**Comment by JirHan** [comment]
Hey, I faced this issue too. It was cause by too many workouts so I had to change the code a bit to load workouts by 100 chunks.

**Comment by axle-h** [comment]
Lol what?! I didn't have enough workouts to trigger this?! Submit a PR please to help others.

**Comment by JirHan** [comment]
There you go ;)

**Comment by axle-h** [comment]
I've not tried it as clearly I'm not active enough, but this looks to be fixed. I'll create a new release when I get onto my Windows machine later. Thanks guys.
